name: medicamina_api
description: Open source precision medicine API.
version: 1.0.0+1
repository: https://github.com/medicamina/api
issue_tracker: https://github.com/medicamina/api/issues
documentation: https://docs.medicamina.us/
funding: https://patreon.com/medicamina_github

publish_to: 'none'

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.1
  orm: ^3.4.5
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
